= Exercitii care insotesc studiul individual (Hibernate): Self-study Exercises (Hibernate)
:experimental:

== Aplicatie multitenant (baze de date separate)

. Creeaza baza de date _store1_. In acesta baza de date creeaza tabelul _products_ cu coloanele: _id_, _name_, _price_.
Creeaza a doua baza de date - _store2_. In _store2_, la fel, creeaza tabelul _products_.

Verificare:: In _store1_ comanda SQL care urmeaza trebuie sa se execute fara erori
+
[source, sql]
----
INSERT INTO products (name, price) VALUES ('product11', 11.00), ('product12', 12.00);
----
+
iar in _store2_:
+
[source, sql]
----
INSERT INTO products (name, price) VALUES ('product21', 21.00), ('product22', 22.00);
----

. Elaboreaza o aplicatie web simpla care utilizeaza Spring Boot si are incluse dependintele pentru conexiunea la baza de date.
Creeaza entitatea `Product` corespunzatoare tabelului `products`. Creeaza `ProductRepository` corespunzatoare entitatii.
Sugestie:: https://start.spring.io/, alege Java 8, iar din dependinte include _Spring Web_ si _Spring Data JPA_.

Verificare:: creeaza rest controlerul `ProductController`, injecteaza `ProductRepository`, creeaza o metoda mapata la adresa _/products/_ 
care apeleaza `findAll()` si intoarce rezultatul; porneste proiectul si acceseaza http://localhost:8080/products/

. Vom extragea crearea obiectului `DataSource` din interiorul Spring-ului nemijlocit in aplicatie, creeaza clasa:
+
[source, java]
----
@Configuration
public class AppConfig {

    @Bean
    @Primary
    @ConfigurationProperties(prefix="spring.store1-datasource")
    public DataSource store1DataSource() {
        return DataSourceBuilder.create().build();
    }
}
----
+
iar in _application.properties_ redenumeste toate proprietatile care incep cu _spring.datasource._ in _spring.store1-datasource._.

. Adauga informatie de conectare pentru a ii-a baza de date.

Sugestie:: la al ii-lea bean de tip `DataSource` nu pune adnotarea `@Primary`.

. Intra pe https://docs.jboss.org/hibernate/core/4.3/devguide/en-US/html/ si deschide capitolul _16. Multi-tenancy_.
Citeste in general despre abordarea de care avem noi nevoie _16.2.1. Separate database_. Apoi la ceea ce ofera Hibernate,
_16.3. Multi-tenancy in Hibernate_ (e vorba de doua clase). In _application.properties_:
+
[source, properties]
----
spring.jpa.properties.hibernate.hibernate.multiTenancy=DATABASE
----
+
toate valorile sunt enumerate in `org.hibernate.MultiTenancyStrategy`.


https://www.baeldung.com/hibernate-5-multitenancy
https://vladmihalcea.com/hibernate-database-catalog-multitenancy/
https://medium.com/swlh/multi-tenancy-implementation-using-spring-boot-hibernate-6a8e3ecb251a

